
name: Updating BLS Data

on:
  push:
    branches:
      - master
  schedule:
    - cron: "30 13 15 * *"

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Update BLS Data
        run: python retrive_last_month.py

      - name: Commit and push updated data
        run: |
          git config --global user.name "pranavtej07"
          git config --global user.email "pranavtej07@gmail.com"
          git add .
          git commit -m "Add folder and load CSVs" || echo "No changes to commit"
          git push
